[tool.bumpversion]
current_version = "0.5.2"

[[tool.bumpversion.files]]
filename = "python/screenValidator/version.py"


[[tool.bumpversion.files]]
filename = "README.md"
search = "screenValidator v{current_version}"
replace = "screenValidator v{new_version}"