[tool.bumpversion]
current_version = "0.6.1"

[[tool.bumpversion.files]]
filename = "python/ETDQualitizer/version.py"


[[tool.bumpversion.files]]
filename = "README.md"
search = "ETDQualitizer v{current_version}"
replace = "ETDQualitizer v{new_version}"