name: Create release and build and attach MATLAB MLTBX 📦 file

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  matlab_dist:
    name: Make matlab MLTBX 📦, create release and attach MLTBX 📦 to release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Create MLTBX
        uses: matlab-actions/run-command@v2
        continue-on-error: false
        with:
          command: addpath([pwd filesep 'packaging']); createETDQ_MLTBX('packaging/ETDQualitizer.prj','${{  github.ref_name }}')

      - name: Upload mltbx as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: matlab_mltbx
          path: ./${{  github.ref_name }}.mltbx

      - name: Create release with mltbx atached
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          draft: true
          name: ${{ github.ref_name }}
          files: ./${{  github.ref_name }}.mltbx

  CRAN_package:
    name: Build CRAN package 📦 and attach 📦 to release
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("devtools", "usethis", "rcmdcheck"))'

      - name: Run checks
        working-directory: r/ETDQualitizer
        run: |
          Rscript -e 'devtools::check(document = FALSE)'

      - name: Build package
        working-directory: r/ETDQualitizer
        run: |
          Rscript -e 'devtools::build(path = "../../pkg_build")'

      - name: Get version
        id: get_version
        working-directory: r/ETDQualitizer
        run: |
          Rscript -e 'version <- as.character(devtools::as.package(".")$version); writeLines(paste0("version=", version), Sys.getenv("GITHUB_OUTPUT"))'

      - name: Upload CRAN package as release artifact
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          files: pkg_build/*.tar.gz
